version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229 # debugger
    environment:
      - NODE_ENV=development
    volumes:
      - './server:/app'
      ## Enable HMR https://medium.com/@kartikio/setup-node-ts-local-development-environment-with-docker-and-hot-reloading-922db9016119
      - ignore:/app/node_modules/
    restart: always

  ui: 
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - './ui:/app'
      ## Enable HMR https://medium.com/@kartikio/setup-node-ts-local-development-environment-with-docker-and-hot-reloading-922db9016119
      - ignore2:/app/node_modules/
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  ignore:
  ignore2:
  mongodb_data: